## 问题

以 [Restormer-Plus](https://github.com/ZJLAB-AMMI/Restormer-Plus) 为例

clone 后目录结构如下：

```
├── 略
└── restormer_x
    ├── dataset
    │   ├── gt_rain_dataset.py
    │   └── __init__.py
    ├── __init__.py
    ├── model
    │   ├── __init__.py
    │   └── restormer.py
    ├── test.py
    ├── train.py
    └── utils
        ├── data_augmentation.py
        ├── __init__.py
        └── 略
```

`./restormer_x/train.py` 中有以下代码段：

```python
from restormer_x.dataset.gt_rain_dataset import get_datasets
from restormer_x.model.restormer import get_model
from restormer_x.utils.log import set_logger
from restormer_x.utils.loss import ShiftMSSSIM
from restormer_x.utils.trainutil import get_train_settings, train
```

根据 README 提示，在项目根目录执行 `python ./restormer_x/train.py`，提示找不到 `restormer_x` 包。在根目录进入 Python Shell，手动执行上面的命令：

```python
from restormer_x.dataset.gt_rain_dataset import get_datasets
```

可以正常导入。

## 排查

上网搜索后，在 Python Shell 中执行以下命令：

```python
import sys
print(sys.path)
```

输出如下：

```
['', '/root/miniconda3/lib/python38.zip', '/root/miniconda3/lib/python3.8', '/root/miniconda3/lib/python3.8/lib-dynload', '/root/miniconda3/lib/python3.8/site-packages']
```

在上面提到的 `train.py` 中执行同样命令，输出如下：

```
['/root/bishe/Restormer-Plus/restormer_x', '/root/miniconda3/lib/python38.zip', '/root/miniconda3/lib/python3.8', '/root/miniconda3/lib/python3.8/lib-dynload', '/root/miniconda3/lib/python3.8/site-packages']
```

发现脚本的根目录变成了 `restormer_x`。

尝试使用 `os.chdir`，无果。

## 解决

根据网上搜索，在代码开头添加如下内容：

```python
import sys
root_dir = os.path.dirname(os.path.dirname(__file__))
sys.path.insert(0, root_dir)
```

即：将当前文件所在目录的父目录添加到 `sys.path` 中。

问题解决。